### ISSUE TITLE
page no longer loads

### ISSUE THREAD

**Issue by VinSpee** [tedconf/tedconf.github.io#1]
Hi!

I was attempting to add a new project to this page, but after cloning, installing, and `ember s`ing, the build succeeds, but the dev server throws these errors in the console:

<img width="1009" alt="screen shot 2016-06-03 at 10 39 47 am" src="https://cloud.githubusercontent.com/assets/582828/15782307/bfaffcd8-2977-11e6-82db-bce8a3c17398.png">

**Comment by jwarchol** [comment]
![](https://i.imgflip.com/158hii.jpg)
